Add warning reporting when missing epochs filtered more than 10% of data
bachlab/PsPM pull request #339
Opened 2021-12-13 19:18 UTC by teddychao

Fixes #338.

Changes proposed in this pull request:
- Add a warning when input data was filtered out more than 10% due to missing epoch detection.

2021-12-21 09:35 UTC, dominikbach requested changes

2022-01-07 22:18 UTC, dominikbach approved these changes

2022-01-07 22:18 UTC, merged

2023-02-07 18:03 UTC, m-guggenmos commented
Just to make sure, is this line in the fix correct?
```matlab
perc_missing = 1 - sum(glm.M)/length(glm.M);
```
I'm getting a warning related to this variable a lot and intuitively it makes more sense without the `1 -`? I'm not familiar with the codebase though.

2023-02-08 18:38 UTC, teddychao commented
> Just to make sure, is this line in the fix correct?
> 
> ```matlab
> perc_missing = 1 - sum(glm.M)/length(glm.M);
> ```
> 
> I'm getting a warning related to this variable a lot and intuitively it makes more sense without the `1 -`? I'm not familiar with the codebase though.

Hi @m-guggenmos,
Thank you for propose the issue to us. Yes it is a mistake. The positive values in `M` and `glm.M` denote missing values, thus the `perc.missing` should not contain a `1-` there.
We apologise for any inconenience the mistake brought to you. We will include this fix in our next release that will be available very soon.
Best wishes
Teddy

2023-02-08 21:06 UTC, m-guggenmos commented
Great, thanks for the prompt response!