Fix issue 356 - pspm_convert_time2index
bachlab/PsPM pull request #357
Opened 2022-03-09 01:17 UTC by teddychao

Fixes #356

Changes proposed in this pull request:
- Update `pspm_time2index` to `pspm_convert_time2index`
- Update keyword `'b'` to keyward `'c'` indicating combined
- Generalise `pspm_convert_xxx` functions
- Document `pspm_convert_xxx` functions

2022-03-12 08:15 UTC, dominikbach commented
It seems that the "convert" functions are data conversion functions which users might like to use directly for data processing, whereas time2index is a in internal convenience function; hence I'd suggest to keep the name?

2022-03-12 08:16 UTC, dominikbach commented
But it seems plausible to rename the other data conversion functions, such as hb2hp etc.

2022-03-12 08:16 UTC, dominikbach commented
However, there are many more of this sort.

2022-03-12 08:16 UTC, dominikbach requested changes
see comments.

2022-03-21 12:13 UTC, teddychao commented
The function `normrnd` is used by some test functions, like `pspm_load1_data`, but it requires statistics and machine learning toolbox. The init function should make this clear.

2022-04-26 15:39 UTC, dominikbach approved these changes

2022-04-27 01:32 UTC, teddychao commented on src/pspm_convert_area2diameter.m
> +      '(square)?(centi|milli|deci|c|m|d)?(m(et(er|re))?)(s?\^?2?)', ...
@jbrochar I agree, however I have no idea about what it means either, it is written by Tobias...

2022-04-27 01:34 UTC, teddychao commented on src/pspm_convert_pixel2unit.m
> +
Yes, there have been no blank lines in this function now.

2022-04-27 14:03 UTC, merged