Update pspm_sf relevant functions
bachlab/PsPM pull request #502
Opened 2023-07-17 12:41 UTC by teddychao

Fixes # .
Update SF functions 
Changes proposed in this pull request:
- update sf series functions
- 
-

2023-08-07 14:18 UTC, dominikbach requested changes
There is one question; I also left this question in the other pull request.

2023-08-11 08:52 UTC, dominikbach commented
Apparently all changes were already commited with another merge request. Can the request be closed?

2023-08-11 13:18 UTC, dominikbach approved these changes

2023-08-11 17:33 UTC, teddychao commented on src/pspm_cfg/pspm_cfg_sf.m
> +mrk_chan.val     = {1};
I have revert this back to {1}. This is because I misunderstood first marker channel and last data channel when I modified this..

2023-08-11 18:22 UTC, teddychao commented
> Apparently all changes were already commited with another merge request. Can the request be closed?

Yes I will do now.
I did not close this because I have not tested the question you mentioned. I tested the data from our user and confirmed that there is no issue when running the SF analysis with the current specifications.

2023-08-11 18:22 UTC, merged