fix DCM for NaN data
bachlab/PsPM pull request #645
Opened 2024-02-29 08:32 UTC by dominikbach

Fixes #644  .

Changes proposed in this pull request:
- account for an edge case when all data are NaN

2024-02-29 08:32 UTC, dominikbach commented
@teddychao Could you kindly add a test case with only NaN data?

2024-03-04 12:01 UTC, teddychao approved these changes

2024-03-04 12:54 UTC, teddychao requested changes
The original `isempty` in line 277 is not quite working. At line 275, `isnan` will return an array such as `[0,1,0]`, in which `0` and `1` are logical. However, if we type `isempty(isnan([1,2,3]))`, it will return `0`, which means `isnan([1,2,3])` is not empty, and there is `nan` in `[1,2,3]`. This is not correct. If we use `any(isnan([1,2,3]))`, we also get `0`, but this correct, because there is no `nan` in `[1,2,3]`.

2024-03-04 14:18 UTC, teddychao approved these changes

2024-03-04 14:19 UTC, teddychao commented
@dominikbach I fixed the issues I mentioned above in the commits. I also added the test for missing values as `test_hra1_flex_cs_missing`. Maybe you can have a look and merge if you are happy with them. Thanks

2024-03-04 17:12 UTC, merged