Unify function output
bachlab/PsPM pull request #689
Opened 2024-04-17 18:54 UTC by dominikbach

Fixes # .

Changes proposed in this pull request:
- 
- 
-

2024-04-19 13:40 UTC, teddychao commented
Hi Dom,

Thank you for the update.

My flight is tomorrow and I am preparing for several stuffs. Is it ok if I review this next week?

Best wishes
Teddy

From: Dominik Bach ***@***.***>
Date: Friday, 19 April 2024 at 09:29
To: bachlab/PsPM ***@***.***>
Cc: Teddy ***@***.***>, Review requested ***@***.***>
Subject: Re: [bachlab/PsPM] Unify function output (PR #689)

@dominikbach<https://github.com/dominikbach> requested your review on: #689<https://github.com/bachlab/PsPM/pull/689> Unify function output.

—
Reply to this email directly, view it on GitHub<https://github.com/bachlab/PsPM/pull/689#event-12534768462>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA5W62TSH2LVJPQBERKYIDLY6DIX5AVCNFSM6AAAAABGL33LHKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGUZTINZWHA2DMMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2024-05-13 15:11 UTC, teddychao requested changes
I have reviewed some functions.. I try to finish them in these two days.

2024-05-13 19:16 UTC, teddychao requested changes

2024-05-13 19:16 UTC, teddychao commented on src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
>          winfo = struct();
Think this line can be removed.

2024-05-13 19:16 UTC, teddychao commented on src/pspm_find_sounds.m
> +%   [sts, channel_index, info] = pspm_find_sounds(fn, options)
Maybe consistent variable naming is required here too

2024-05-13 19:16 UTC, teddychao commented on src/pspm_find_sounds.m
> +% ├.channel_action: ['add'/'replace']
We may want to discuss about whether we would like to keep the optional value `none` for `channel_action` ?

2024-05-14 14:07 UTC, dominikbach commented on src/pspm_check_data.m
1. the output variable `data` is an altered version of the input with legacy and format  conversions (e.g. line 53) so should be kept.
2. Numbering in comments removed now.

2024-05-14 14:26 UTC, dominikbach commented on src/pspm_cfg/pspm_cfg_rename.m
> +newfilename.num     = [1 1];
fixed now.

2024-05-15 17:00 UTC, dominikbach commented on src/pspm_cfg/pspm_cfg_run_find_sounds.m
We always want to create a channel (i.e. never give the GUI user the option not to). But this was incorrectly implemented in the GUI. It should be fixed now.

2024-05-15 17:01 UTC, dominikbach commented on src/pspm_sf_mp.m
> +%   [sts, mp] = pspm_sf_mp(model, options)
This is just stylistic and does not impair functionality.

2024-05-15 17:02 UTC, dominikbach commented on src/pspm_pupil_correct_eyelink.m
> +%   [sts, channel_index] = pspm_pupil_correct_eyelink(fn, options)
Just stylistic.

2024-05-15 17:03 UTC, dominikbach commented on src/pspm_convert_ecg2hb_amri.m
> +%   [sts, channel_index] = pspm_convert_ecg2hb_amri(fn)
Just stylistic.

2024-05-15 17:04 UTC, dominikbach commented on src/pspm_convert_hb2hp.m
> +%   [sts, channel_index] = pspm_convert_hb2hp(fn, sr, options)
Just stylistic.

2024-05-15 17:04 UTC, dominikbach commented on src/pspm_convert_ppg2hb.m
> +%   [sts, channel_index] = pspm_convert_ppg2hb( fn, options )
Just stylistic.

2024-05-21 12:43 UTC, dominikbach commented on src/pspm_sf_dcm.m
> +%   [sts, dcm] = pspm_sf_dcm(model, options)
This is a stylistic issue, no change.

2024-05-21 12:43 UTC, dominikbach commented on src/pspm_sf_auc.m
This is a stylistic issue, no change.

2024-05-21 12:44 UTC, dominikbach commented on src/pspm_version.m
removed now.

2024-05-21 12:49 UTC, dominikbach commented on src/pspm_merge.m
> +    [sts_load_data, infos, data] = pspm_load_data(infile{iNum});
Thanks for spotting this; `pspm_cfg_run_merge` is fixed now.

2024-05-21 12:54 UTC, dominikbach commented on src/pspm_cfg/pspm_cfg_run_rename.m
Thank you, this is fixed now.

2024-05-21 13:12 UTC, teddychao approved these changes

2024-05-21 17:00 UTC, dominikbach commented on src/pspm_combine_markerchannels.m
> +function [sts, outchannel] = pspm_combine_markerchannels(datafile, options)
GUI dependencies & tests will be updated in future PR, no change required for now.

2024-05-21 17:01 UTC, dominikbach commented on src/pspm_convert_ecg2hb.m
> +%   [sts, channel_index, quality_info] = pspm_convert_ecg2hb(fn, options)
Stylistic issue, no change required.

2024-05-21 17:02 UTC, dominikbach commented on src/pspm_cfg/pspm_cfg_run_pp_emg_data.m
> +  out = {outchannel};
GUI dependencies will be updated in a future PR.

2024-05-21 17:03 UTC, dominikbach commented on test/pspm_convert_gaze_test.m
> +      this.fn = this.fn;
Fixed.

2024-05-21 17:04 UTC, dominikbach commented on src/pspm_cfg/pspm_cfg_run_pp_heart_data.m
>          winfo = struct();
?

2024-05-21 18:05 UTC, merged