added path handling in pspm_init and pspm_quit
bachlab/PsPM pull request #713
Opened 2024-05-31 22:59 UTC by MadniAbdulWahab

Fixes #668  .

Changes proposed in this pull request:
- Defined directories and added necessary paths in pspm_init.
- Removed the paths in pspm_quit which were added in pspm_init.

2024-06-10 15:23 UTC, teddychao commented
I think the PsPM folders in this list shall be excluded into the path list for being added to MATLAB.
<img width="868" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/5fbef289-43ce-4468-9b9b-7f1eb8028ec1">
It is recommended to only add those folders instead of folders and their subfolders.

2024-06-10 15:23 UTC, teddychao requested changes

2024-06-10 15:23 UTC, teddychao commented on src/pspm_init.m
> +required_folders = {'backroom', 'ext', 'Import', 'pspm_cfg'};
Perhaps it is useful to ask @dominikbach if `backroom` is expected here. I remember `backroom` is expected to be excluded in a previous commit but I am not fully certain.

2024-07-01 01:33 UTC, teddychao commented
This is now finished.

Before starting PsPM
<img width="912" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/4461c3f5-8659-4df4-9404-afbfb2edf52a">

When PsPM is running
<img width="912" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/aee45eb7-2d16-4b17-9c2b-4305ec9931aa">

After quitting PsPM
<img width="912" alt="image" src="https://github.com/bachlab/PsPM/assets/3895146/a300e745-b88c-4332-9c16-bd1b7271cb64">

2024-07-01 11:53 UTC, teddychao commented
### Discussion 01.07.2024

The key tasks
1. The subfolders may cause issues if they are all added to MATLAB. The essential subfolders need to be identified. Other folders which may cause conflicts shall be excluded to the subfolder list (the essential subfolders).
2. SPM may cause incompatibility when users run PsPM with SPM path added. This shall be solved by adding a warning in `pspm_init` and asking users to remove PsPM.
3. The subfolder list shall be updated at the beginning of `pspm_init`. This needs to be managed by PsPM automatically without asking users to do that.

2024-07-01 11:58 UTC, dominikbach commented
To add on the previous points:
1. If SPM or Matlabbatch installations (outside PsPM folders) are on the path already, interrupt start up and give an error.
2. If any conflicting PsPM subfolders are on the path, interrupt startup and give an error.
3. Add root (src) folder to list of essential folders to be added to the path on startup.

2024-07-15 03:18 UTC, teddychao commented
Examples

Warning dialog
<img width="620" alt="image" src="https://github.com/user-attachments/assets/030a094b-d439-47c2-9960-0138724c5fb9">

Error
<img width="566" alt="image" src="https://github.com/user-attachments/assets/ff72fdba-b187-440a-a9e3-cd037f37716b">

2024-07-15 03:19 UTC, teddychao commented
Hi @dominikbach This has been completed. Please may I ask you to test and let me know if you are happy with this version. Thanks.

2024-07-15 11:30 UTC, teddychao approved these changes

2024-07-16 16:46 UTC, merged